In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import seaborn

In [5]:
dataset=pd.read_csv("electronics.csv")
dataset.head()

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,0,5.0,1999-06-13,Female,Portable Audio & Video,NaN,1999,NaN,0
1,0,1,5.0,1999-06-14,Female,Portable Audio & Video,NaN,1999,NaN,0
2,0,2,3.0,1999-06-17,Female,Portable Audio & Video,NaN,1999,NaN,0
3,0,3,1.0,1999-07-01,Female,Portable Audio & Video,NaN,1999,NaN,0
4,0,4,2.0,1999-07-06,Female,Portable Audio & Video,NaN,1999,NaN,0

In [7]:
dataset.tail

<bound method NDFrame.tail of          item_id  user_id  rating   timestamp model_attr  \
0              0        0     5.0  1999-06-13     Female
1              0        1     5.0  1999-06-14     Female
2              0        2     3.0  1999-06-17     Female
3              0        3     1.0  1999-07-01     Female
4              0        4     2.0  1999-07-06     Female
...          ...      ...     ...         ...        ...
1292949     9478  1157628     1.0  2018-09-26     Female
1292950     9435  1157629     5.0  2018-09-26     Female
1292951     9305  1157630     3.0  2018-09-26     Female
1292952     9303  1157631     5.0  2018-09-29       Male
1292953     9478  1157632     1.0  2018-10-01     Female

                        category       brand  year user_attr  split
0         Portable Audio & Video         NaN  1999       NaN      0
1         Portable Audio & Video         NaN  1999       NaN      0
2         Portable Audio & Video         NaN  1999       NaN      0
3         Portable Audio & Video         NaN  1999       NaN      0
4         Portable Audio & Video         NaN  1999       NaN      0
...                          ...         ...   ...       ...    ...
1292949               Headphones  Etre Jeune  2017       NaN      0
1292950  Computers & Accessories         NaN  2017       NaN      0
1292951  Computers & Accessories         NaN  2016       NaN      0
1292952               Headphones         NaN  2018       NaN      0
1292953               Headphones  Etre Jeune  2017    Female      0

[1292954 rows x 10 columns]>

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1292954 entries, 0 to 1292953
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   item_id     1292954 non-null  int64
 1   user_id     1292954 non-null  int64
 2   rating      1292954 non-null  float64
 3   timestamp   1292954 non-null  object
 4   model_attr  1292954 non-null  object
 5   category    1292954 non-null  object
 6   brand       331120 non-null   object
 7   year        1292954 non-null  int64
 8   user_attr   174124 non-null   object
 9   split       1292954 non-null  int64
dtypes: float64(1), int64(4), object(5)
memory usage: 98.6+ MB

In [9]:
from datetime import datetime
pd.to_datetime(dataset["timestamp"]) #Convertir le

0         1999-06-13
1         1999-06-14
2         1999-06-17
3         1999-07-01
4         1999-07-06
             ...
1292949   2018-09-26
1292950   2018-09-26
1292951   2018-09-26
1292952   2018-09-29
1292953   2018-10-01
Name: timestamp, Length: 1292954, dtype: datetime64[ns]

In [12]:
dataset['brand']=dataset['brand'].astype(str)

In [14]:
dataset['category']=dataset['category'].astype(str)

In [16]:
dataset['timestamp']=pd.to_datetime(dataset['timestamp'])

In [17]:
dataset

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,0,5.0,1999-06-13,Female,Portable Audio & Video,nan,1999,NaN,0
1,0,1,5.0,1999-06-14,Female,Portable Audio & Video,nan,1999,NaN,0
2,0,2,3.0,1999-06-17,Female,Portable Audio & Video,nan,1999,NaN,0
3,0,3,1.0,1999-07-01,Female,Portable Audio & Video,nan,1999,NaN,0
4,0,4,2.0,1999-07-06,Female,Portable Audio & Video,nan,1999,NaN,0
...,...,...,...,...,...,...,...,...,...,...
1292949,9478,1157628,1.0,2018-09-26,Female,Headphones,Etre Jeune,2017,NaN,0
1292950,9435,1157629,5.0,2018-09-26,Female,Computers & Accessories,nan,2017,NaN,0
1292951,9305,1157630,3.0,2018-09-26,Female,Computers & Accessories,nan,2016,NaN,0
1292952,9303,1157631,5.0,2018-09-29,Male,Headphones,nan,2018,NaN,0
1292953,9478,1157632,1.0,2018-10-01,Female,Headphones,Etre Jeune,2017,Female,0

In [26]:
dataset["rating"]=dataset["rating"].astype(float)

In [28]:
dataset["user_id"]=dataset['user_id'].astype(str)

In [34]:
dataset["item_id"]=dataset["item_id"].astype(str)